[project]
name = "ygopyro"
version = "0.1.4.fix1"
description = ""
readme = "README.md"
authors = [
    { name = "jwyxym", email = "jwyxym@126.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ygopyro = "ygopyro:main"

[tool.maturin]
module-name = "ygopyro._core"
python-packages = ["ygopyro"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "maturin>=1.15.0",
]
